In [1]:
import numpy as np

In [3]:
#Mathematical Operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a =", a)
print("b =", b)
print("\na + b =", a + b)
print("a * b =", a * b)
print("a**2 =", a**2)
print("b**2 =", b**2)
print("sqrt =", np.sqrt(a))
print("sqrt =", np.sqrt(b))

a = [1 2 3 4 5]
b = [10 20 30 40 50]

a + b = [11 22 33 44 55]
a * b = [ 10  40  90 160 250]
a**2 = [ 1  4  9 16 25]
b**2 = [ 100  400  900 1600 2500]
sqrt = [1.         1.41421356 1.73205081 2.         2.23606798]
sqrt = [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [4]:
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("Matrix Multiplication (mat1 @ mat2):\n", mat1 @ mat2)

Matrix Multiplication (mat1 @ mat2):
 [[19 22]
 [43 50]]


In [23]:
#Axis-wise, and statistical
scores = np.array([[85, 90, 78],
                   [92, 88, 76],
                   [70, 95, 83],
                   [88, 72, 91]])

print("Scores is:\n", scores)
print("\n---Overall Statiscal---")
print("Mean of score:\n", np.mean(scores))
print("Median of score:\n", np.median(scores))
print("Std Dev:\n", np.std(scores).round(2))
print("Min:", np.min(scores), "| Max:",np.max(scores))

print("\n---Axis Wise---")
print("Subject Wise Mean - Axis = 0:", np.mean(scores,axis=0))
print("Student wise Mean - Axis = 1 :", np.mean(scores , axis= 1).round(2))
print("Subject Wise Max - Axis = 0:", np.max(scores,axis=0))
print("Student-wise Sum (axis=1):", np.sum(scores, axis=1))

Scores is:
 [[85 90 78]
 [92 88 76]
 [70 95 83]
 [88 72 91]]

---Overall Statiscal---
Mean of score:
 84.0
Median of score:
 86.5
Std Dev:
 7.87
Min: 70 | Max: 95

---Axis Wise---
Subject Wise Mean - Axis = 0: [83.75 86.25 82.  ]
Student wise Mean - Axis = 1 : [84.33 85.33 82.67 83.67]
Subject Wise Max - Axis = 0: [92 95 91]
Student-wise Sum (axis=1): [253 256 248 251]
