In [1]:
import numpy as np

In [13]:
arr = np.arange(1,13)
print("Original 1D array:", arr)

reshaped = arr.reshape(3,4)
print("Reshaped:\n", reshaped)

reshaped2 = arr.reshape(2,2,3)
print("Reshaped :\n", reshaped2)

print("\nFlatten back:", reshaped.flatten())
print("Transpose:\n", reshaped.T)

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flatten back: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [15]:
# Broadcasting
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_vector = np.array([10, 20, 30])

print("Matrix:\n", matrix)
print("\nRow Vector:", row_vector)
print("\nMatrix + Row Vector (Broadcasting):\n", matrix + row_vector)
print("\nMatrix * 2 (Scalar Broadcasting):\n", matrix * 2)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row Vector: [10 20 30]

Matrix + Row Vector (Broadcasting):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Matrix * 2 (Scalar Broadcasting):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [17]:
# Save single array
data_to_save = np.random.randint(1, 100, size=(5, 5))
print("Data to Save:\n", data_to_save)

np.save("my_array.npy", data_to_save)
print("\n Saved as my_array.npy")

# Load it back
loaded = np.load("my_array.npy")
print("\n Loaded Array:\n", loaded)
print("\nArrays match:", np.array_equal(data_to_save, loaded))

Data to Save:
 [[47 87 19 90 14]
 [22 81 38 88 80]
 [13 25 44 48 70]
 [36 85 88 29 43]
 [ 8 64 65  9 94]]

 Saved as my_array.npy

 Loaded Array:
 [[47 87 19 90 14]
 [22 81 38 88 80]
 [13 25 44 48 70]
 [36 85 88 29 43]
 [ 8 64 65  9 94]]

Arrays match: True


In [20]:
# Save multiple arrays
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([10.5, 20.5, 30.5])

np.savez("multiple_arrays.npz", array_a=arr_a, array_b=arr_b)
print(" Saved multiple arrays as multiple_arrays.npz")

loaded_npz = np.load("multiple_arrays.npz")
print("\nLoaded array_a:", loaded_npz["array_a"])
print("Loaded array_b:", loaded_npz["array_b"])


 Saved multiple arrays as multiple_arrays.npz

Loaded array_a: [1 2 3 4 5]
Loaded array_b: [10.5 20.5 30.5]


In [22]:
# Save as CSV (txt)
np.savetxt("array_data.csv", data_to_save, delimiter=",", fmt="%d")
loaded_csv = np.loadtxt("array_data.csv", delimiter=",")
print(" Saved & Loaded from CSV")
print("CSV Loaded Data:\n", loaded_csv.astype(int))

 Saved & Loaded from CSV
CSV Loaded Data:
 [[47 87 19 90 14]
 [22 81 38 88 80]
 [13 25 44 48 70]
 [36 85 88 29 43]
 [ 8 64 65  9 94]]
